collections:
  - name: awx.awx
  - name: azure.azcollection
  - name: amazon.cloud
  - name: amazon.aws
    version: 4.3.0
  - name: theforeman.foreman
  - name: google.cloud
  - name: openstack.cloud
  - name: community.vmware
    version: 2.9.0
  - name: community.aws
    version: 4.3.0
  - name: ovirt.ovirt
  - name: ansible.posix
  - name: ansible.windows
  - name: community.general
  - name: community.windows
  - name: community.azure
  - name: community.kubernetes
    version: 1.2.1
  - name: community.kubevirt
  - name: community.okd
  - name: kubernetes.core
    version: 2.1.1
  - name: ansible.netcommon
  - name: vmware.vmware_rest
  #- name: chocolatey.chocolatey # requirements conflict with community.vmware